# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('time', models.DateField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=1024, null=True)),
                ('describe', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=1024)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Album', verbose_name='\u4e13\u8f91')),
            ],
        ),
        migrations.CreateModel(
            name='MusicLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(blank=True, max_length=1024, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.MusicLanguage', verbose_name='\u8bed\u79cd')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='singer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Singer', verbose_name='\u6b4c\u624b'),
        ),
    ]
